const galeriaImages = [
  { id: 1, src: require("../images/Galeria/img_01.jpg")},
  { id: 2, src: require("../images/Galeria/img_33.jpg")},
  { id: 3, src: require("../images/Galeria/img_03.jpg")},
  { id: 4, src: require("../images/Galeria/img_04.jpg")},
  { id: 5, src: require("../images/Galeria/img_08.jpg")},
  { id: 5, src: require("../images/Galeria/img_09.jpg")},
  { id: 5, src: require("../images/Galeria/img_10.jpg")},
  { id: 5, src: require("../images/Galeria/img_11.jpg")},
  { id: 5, src: require("../images/Galeria/img_12.jpg")},
  { id: 5, src: require("../images/Galeria/img_13.jpg")},
  { id: 5, src: require("../images/Galeria/img_14.jpg")},
  { id: 5, src: require("../images/Galeria/img_15.jpg")},
  { id: 5, src: require("../images/Galeria/img_16.jpg")},
  { id: 5, src: require("../images/Galeria/img_17.jpg")},
  { id: 5, src: require("../images/Galeria/img_18.jpg")},
  { id: 5, src: require("../images/Galeria/img_19.jpg")},
  { id: 5, src: require("../images/Galeria/img_20.jpg")},
  { id: 5, src: require("../images/Galeria/img_21.jpg")},
  { id: 5, src: require("../images/Galeria/img_22.jpg")},
  { id: 5, src: require("../images/Galeria/img_23.jpg")},
  { id: 5, src: require("../images/Galeria/img_24.jpg")},
  { id: 5, src: require("../images/Galeria/img_25.jpg")},
  { id: 5, src: require("../images/Galeria/img_26.jpg")},
  { id: 5, src: require("../images/Galeria/img_27.jpg")},
  { id: 5, src: require("../images/Galeria/img_28.jpg")},
  { id: 5, src: require("../images/Galeria/img_29.jpg")},
  { id: 5, src: require("../images/Galeria/img_30.jpg")},
  { id: 5, src: require("../images/Galeria/img_31.jpg")},
  { id: 5, src: require("../images/Galeria/img_32.jpg")},
  { id: 5, src: require("../images/Galeria/img_35.jpg")},
  { id: 5, src: require("../images/Galeria/img_36.jpg")},
  { id: 5, src: require("../images/Galeria/img_37.jpg")},
  { id: 5, src: require("../images/Galeria/img_38.jpg")},
  { id: 5, src: require("../images/Galeria/img_39.jpg")},
  { id: 5, src: require("../images/Galeria/img_40.jpg")},
  { id: 5, src: require("../images/Galeria/img_41.jpg")},
  { id: 5, src: require("../images/Galeria/img_42.jpg")},
  { id: 5, src: require("../images/Galeria/img_43.jpg")},
  { id: 5, src: require("../images/Galeria/img_44.jpg")},
  { id: 5, src: require("../images/Galeria/img_45.jpg")},
  { id: 5, src: require("../images/Galeria/img_47.jpg")},
  { id: 5, src: require("../images/Galeria/img_48.jpg")},
  { id: 5, src: require("../images/Galeria/img_49.jpg")},
  { id: 5, src: require("../images/Galeria/img_50.jpg")},
  { id: 5, src: require("../images/Galeria/img_51.jpg")},
  { id: 5, src: require("../images/Galeria/img_52.jpg")},
  { id: 5, src: require("../images/Galeria/img_53.jpg")},
  { id: 5, src: require("../images/Galeria/img_54.jpg")},
  { id: 5, src: require("../images/Galeria/img_55.jpg")},
  { id: 5, src: require("../images/Galeria/img_56.jpg")},
  { id: 5, src: require("../images/Galeria/img_57.jpg")},
  { id: 5, src: require("../images/Galeria/img_58.jpg")},
  { id: 5, src: require("../images/Galeria/img_60.jpg")},
  { id: 5, src: require("../images/Galeria/img_61.jpg")},
  { id: 5, src: require("../images/Galeria/img_62.jpg")},

  // Agregás más fácilmente
];

export default galeriaImages;
